<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/7/3
 * Time: 23:16
 */

namespace Common\Polymorphism;


class Square extends Polygon
{
    public function draw()
    {
//        parent::draw(); // TODO: Change the autogenerated stub
        echo '我画正方形。';
    }

}